[profile.default]
solc = '0.8.28'
# evm_version='paris'
src = 'contracts'
out = 'out'
test = 'test'
libs = ['lib']
# optimizer = true
# optimizer_runs = 200
auto_detect_remappings = false
ignored_error_codes = []
via_ir = true
evm_version = 'shanghai'


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
