/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IAaveV3PositionBalance {
  export type ConditionStruct = {
    asset: AddressLike;
    balance: BigNumberish;
    positionType: BigNumberish;
    comparison: BigNumberish;
    updateable: boolean;
  };

  export type ConditionStructOutput = [
    asset: string,
    balance: bigint,
    positionType: bigint,
    comparison: bigint,
    updateable: boolean
  ] & {
    asset: string;
    balance: bigint;
    positionType: bigint;
    comparison: bigint;
    updateable: boolean;
  };
}

export interface AaveV3PositionBalanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH"
      | "activeCondition"
      | "addAutomationToCondition"
      | "addCondition"
      | "addStrategyToCondition"
      | "automationValid"
      | "automations"
      | "checkCondition"
      | "conditionActive"
      | "deleteCondition"
      | "isUpdateable"
      | "pool"
      | "removeAutomationFromCondition"
      | "removeStrategyFromCondition"
      | "strategies"
      | "strategyValid"
      | "updateCondition"
      | "walletCondition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConditionAdded" | "ConditionDeleted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeCondition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addAutomationToCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addCondition",
    values: [BigNumberish, IAaveV3PositionBalance.ConditionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addStrategyToCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "automationValid",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "automations",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCondition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "conditionActive",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteCondition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUpdateable",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAutomationFromCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeStrategyFromCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategies",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyValid",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCondition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "walletCondition",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAutomationToCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addStrategyToCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "automationValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "automations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUpdateable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAutomationFromCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeStrategyFromCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletCondition",
    data: BytesLike
  ): Result;
}

export namespace ConditionAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    wallet: AddressLike,
    condition: IAaveV3PositionBalance.ConditionStruct
  ];
  export type OutputTuple = [
    id: bigint,
    wallet: string,
    condition: IAaveV3PositionBalance.ConditionStructOutput
  ];
  export interface OutputObject {
    id: bigint;
    wallet: string;
    condition: IAaveV3PositionBalance.ConditionStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionDeletedEvent {
  export type InputTuple = [id: BigNumberish, wallet: AddressLike];
  export type OutputTuple = [id: bigint, wallet: string];
  export interface OutputObject {
    id: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveV3PositionBalance extends BaseContract {
  connect(runner?: ContractRunner | null): AaveV3PositionBalance;
  waitForDeployment(): Promise<this>;

  interface: AaveV3PositionBalanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH: TypedContractMethod<[], [string], "view">;

  activeCondition: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [boolean],
    "view"
  >;

  addAutomationToCondition: TypedContractMethod<
    [id: BigNumberish, action: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  addCondition: TypedContractMethod<
    [_id: BigNumberish, condition: IAaveV3PositionBalance.ConditionStruct],
    [void],
    "nonpayable"
  >;

  addStrategyToCondition: TypedContractMethod<
    [id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  automationValid: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish, action: BigNumberish],
    [boolean],
    "view"
  >;

  automations: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint[]],
    "view"
  >;

  checkCondition: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  conditionActive: TypedContractMethod<
    [_wallet: AddressLike, _id: BigNumberish],
    [boolean],
    "view"
  >;

  deleteCondition: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  isUpdateable: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [boolean],
    "view"
  >;

  pool: TypedContractMethod<[], [string], "view">;

  removeAutomationFromCondition: TypedContractMethod<
    [id: BigNumberish, automation: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  removeStrategyFromCondition: TypedContractMethod<
    [id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  strategies: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint[]],
    "view"
  >;

  strategyValid: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "view"
  >;

  updateCondition: TypedContractMethod<[_id: BigNumberish], [boolean], "view">;

  walletCondition: TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [IAaveV3PositionBalance.ConditionStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeCondition"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "addAutomationToCondition"
  ): TypedContractMethod<
    [id: BigNumberish, action: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCondition"
  ): TypedContractMethod<
    [_id: BigNumberish, condition: IAaveV3PositionBalance.ConditionStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addStrategyToCondition"
  ): TypedContractMethod<
    [id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "automationValid"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish, action: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "automations"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkCondition"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "conditionActive"
  ): TypedContractMethod<
    [_wallet: AddressLike, _id: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "deleteCondition"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isUpdateable"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAutomationFromCondition"
  ): TypedContractMethod<
    [id: BigNumberish, automation: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeStrategyFromCondition"
  ): TypedContractMethod<
    [id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategies"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "strategyValid"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish, strategy: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateCondition"
  ): TypedContractMethod<[_id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "walletCondition"
  ): TypedContractMethod<
    [wallet: AddressLike, id: BigNumberish],
    [IAaveV3PositionBalance.ConditionStructOutput],
    "view"
  >;

  getEvent(
    key: "ConditionAdded"
  ): TypedContractEvent<
    ConditionAddedEvent.InputTuple,
    ConditionAddedEvent.OutputTuple,
    ConditionAddedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionDeleted"
  ): TypedContractEvent<
    ConditionDeletedEvent.InputTuple,
    ConditionDeletedEvent.OutputTuple,
    ConditionDeletedEvent.OutputObject
  >;

  filters: {
    "ConditionAdded(uint32,address,tuple)": TypedContractEvent<
      ConditionAddedEvent.InputTuple,
      ConditionAddedEvent.OutputTuple,
      ConditionAddedEvent.OutputObject
    >;
    ConditionAdded: TypedContractEvent<
      ConditionAddedEvent.InputTuple,
      ConditionAddedEvent.OutputTuple,
      ConditionAddedEvent.OutputObject
    >;

    "ConditionDeleted(uint32,address)": TypedContractEvent<
      ConditionDeletedEvent.InputTuple,
      ConditionDeletedEvent.OutputTuple,
      ConditionDeletedEvent.OutputObject
    >;
    ConditionDeleted: TypedContractEvent<
      ConditionDeletedEvent.InputTuple,
      ConditionDeletedEvent.OutputTuple,
      ConditionDeletedEvent.OutputObject
    >;
  };
}
