/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStrategyVault,
  IStrategyVaultInterface,
} from "../../../contracts/interfaces/IStrategyVault";

const _abi = [
  {
    inputs: [],
    name: "AutomationAlreadyExist",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "condition",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "AutomationNotExecutable",
    type: "error",
  },
  {
    inputs: [],
    name: "AutomationNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "ChangeStrategyInConditionFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeExceedMaxFee",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidActionTarget",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCondition",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidConditionAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidContextKey",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidID",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidNextStepIndex",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidStepArrayLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stepIndex",
        type: "uint256",
      },
    ],
    name: "NoConditionOrActions",
    type: "error",
  },
  {
    inputs: [],
    name: "PaymentTokenNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "PluginExecutionFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "StrategyAlreadyExist",
    type: "error",
  },
  {
    inputs: [],
    name: "StrategyDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "StrategyIsInUse",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "condition",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "UpdateConditionFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "changeAutomationInConditionFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "bytes4",
            name: "selector",
            type: "bytes4",
          },
          {
            internalType: "bytes",
            name: "parameter",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "enum IStrategyVault.ActionType",
            name: "actionType",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "key",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "offset",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "length",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ParamType",
                    name: "paramType",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Parameter",
                name: "parameterReplacement",
                type: "tuple",
              },
            ],
            internalType: "struct IStrategyVault.ContextKey[]",
            name: "inputs",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "key",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "offset",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "length",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ParamType",
                    name: "paramType",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Parameter",
                name: "parameterReplacement",
                type: "tuple",
              },
            ],
            internalType: "struct IStrategyVault.ContextKey",
            name: "output",
            type: "tuple",
          },
          {
            internalType: "uint8",
            name: "result",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct IStrategyVault.Action",
        name: "action",
        type: "tuple",
      },
    ],
    name: "ActionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "automationId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "address",
            name: "conditionAddress",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "id",
            type: "uint32",
          },
          {
            internalType: "uint8",
            name: "result1",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "result0",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct IStrategyVault.Condition",
        name: "condition",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxFeeAmount",
        type: "uint256",
      },
    ],
    name: "AutomationCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "automationId",
        type: "uint32",
      },
    ],
    name: "AutomationDeleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "automationId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeInToken",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeInUSD",
        type: "uint256",
      },
    ],
    name: "AutomationExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "contextId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    name: "ContextVariableStored",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "enabled",
        type: "bool",
      },
    ],
    name: "FeesEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "contextId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "address",
                    name: "conditionAddress",
                    type: "address",
                  },
                  {
                    internalType: "uint32",
                    name: "id",
                    type: "uint32",
                  },
                  {
                    internalType: "uint8",
                    name: "result1",
                    type: "uint8",
                  },
                  {
                    internalType: "uint8",
                    name: "result0",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Condition",
                name: "condition",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes4",
                    name: "selector",
                    type: "bytes4",
                  },
                  {
                    internalType: "bytes",
                    name: "parameter",
                    type: "bytes",
                  },
                  {
                    internalType: "address",
                    name: "target",
                    type: "address",
                  },
                  {
                    internalType: "uint256",
                    name: "value",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ActionType",
                    name: "actionType",
                    type: "uint8",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "key",
                        type: "bytes32",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "offset",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "length",
                            type: "uint256",
                          },
                          {
                            internalType: "enum IStrategyVault.ParamType",
                            name: "paramType",
                            type: "uint8",
                          },
                        ],
                        internalType: "struct IStrategyVault.Parameter",
                        name: "parameterReplacement",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct IStrategyVault.ContextKey[]",
                    name: "inputs",
                    type: "tuple[]",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "key",
                        type: "bytes32",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "offset",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "length",
                            type: "uint256",
                          },
                          {
                            internalType: "enum IStrategyVault.ParamType",
                            name: "paramType",
                            type: "uint8",
                          },
                        ],
                        internalType: "struct IStrategyVault.Parameter",
                        name: "parameterReplacement",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct IStrategyVault.ContextKey",
                    name: "output",
                    type: "tuple",
                  },
                  {
                    internalType: "uint8",
                    name: "result",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Action[]",
                name: "actions",
                type: "tuple[]",
              },
            ],
            internalType: "struct IStrategyVault.StrategyStep[]",
            name: "steps",
            type: "tuple[]",
          },
          {
            internalType: "bytes32",
            name: "contextId",
            type: "bytes32",
          },
        ],
        indexed: false,
        internalType: "struct IStrategyVault.Strategy",
        name: "strategy",
        type: "tuple",
      },
    ],
    name: "StrategyCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
    ],
    name: "StrategyDeleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
    ],
    name: "StrategyExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "stepId",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "bytes4",
            name: "selector",
            type: "bytes4",
          },
          {
            internalType: "bytes",
            name: "parameter",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "enum IStrategyVault.ActionType",
            name: "actionType",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "key",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "offset",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "length",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ParamType",
                    name: "paramType",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Parameter",
                name: "parameterReplacement",
                type: "tuple",
              },
            ],
            internalType: "struct IStrategyVault.ContextKey[]",
            name: "inputs",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "key",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "offset",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "length",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ParamType",
                    name: "paramType",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Parameter",
                name: "parameterReplacement",
                type: "tuple",
              },
            ],
            internalType: "struct IStrategyVault.ContextKey",
            name: "output",
            type: "tuple",
          },
          {
            internalType: "uint8",
            name: "result",
            type: "uint8",
          },
        ],
        indexed: false,
        internalType: "struct IStrategyVault.Action[]",
        name: "actions",
        type: "tuple[]",
      },
    ],
    name: "StrategyStepExecuted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "automation",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "conditionAddress",
                type: "address",
              },
              {
                internalType: "uint32",
                name: "id",
                type: "uint32",
              },
              {
                internalType: "uint8",
                name: "result1",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "result0",
                type: "uint8",
              },
            ],
            internalType: "struct IStrategyVault.Condition",
            name: "condition",
            type: "tuple",
          },
          {
            internalType: "uint32",
            name: "strategyId",
            type: "uint32",
          },
          {
            internalType: "address",
            name: "paymentToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "maxFeeAmount",
            type: "uint256",
          },
        ],
        internalType: "struct IStrategyVault.Automation",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "strategyId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxFeeInUSD",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "address",
            name: "conditionAddress",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "id",
            type: "uint32",
          },
          {
            internalType: "uint8",
            name: "result1",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "result0",
            type: "uint8",
          },
        ],
        internalType: "struct IStrategyVault.Condition",
        name: "condition",
        type: "tuple",
      },
    ],
    name: "createAutomation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "conditionAddress",
                type: "address",
              },
              {
                internalType: "uint32",
                name: "id",
                type: "uint32",
              },
              {
                internalType: "uint8",
                name: "result1",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "result0",
                type: "uint8",
              },
            ],
            internalType: "struct IStrategyVault.Condition",
            name: "condition",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes4",
                name: "selector",
                type: "bytes4",
              },
              {
                internalType: "bytes",
                name: "parameter",
                type: "bytes",
              },
              {
                internalType: "address",
                name: "target",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256",
              },
              {
                internalType: "enum IStrategyVault.ActionType",
                name: "actionType",
                type: "uint8",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "key",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "offset",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "length",
                        type: "uint256",
                      },
                      {
                        internalType: "enum IStrategyVault.ParamType",
                        name: "paramType",
                        type: "uint8",
                      },
                    ],
                    internalType: "struct IStrategyVault.Parameter",
                    name: "parameterReplacement",
                    type: "tuple",
                  },
                ],
                internalType: "struct IStrategyVault.ContextKey[]",
                name: "inputs",
                type: "tuple[]",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "key",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "offset",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "length",
                        type: "uint256",
                      },
                      {
                        internalType: "enum IStrategyVault.ParamType",
                        name: "paramType",
                        type: "uint8",
                      },
                    ],
                    internalType: "struct IStrategyVault.Parameter",
                    name: "parameterReplacement",
                    type: "tuple",
                  },
                ],
                internalType: "struct IStrategyVault.ContextKey",
                name: "output",
                type: "tuple",
              },
              {
                internalType: "uint8",
                name: "result",
                type: "uint8",
              },
            ],
            internalType: "struct IStrategyVault.Action[]",
            name: "actions",
            type: "tuple[]",
          },
        ],
        internalType: "struct IStrategyVault.StrategyStep[]",
        name: "steps",
        type: "tuple[]",
      },
    ],
    name: "createStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "conditionAddress",
                type: "address",
              },
              {
                internalType: "uint32",
                name: "id",
                type: "uint32",
              },
              {
                internalType: "uint8",
                name: "result1",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "result0",
                type: "uint8",
              },
            ],
            internalType: "struct IStrategyVault.Condition",
            name: "condition",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes4",
                name: "selector",
                type: "bytes4",
              },
              {
                internalType: "bytes",
                name: "parameter",
                type: "bytes",
              },
              {
                internalType: "address",
                name: "target",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "value",
                type: "uint256",
              },
              {
                internalType: "enum IStrategyVault.ActionType",
                name: "actionType",
                type: "uint8",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "key",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "offset",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "length",
                        type: "uint256",
                      },
                      {
                        internalType: "enum IStrategyVault.ParamType",
                        name: "paramType",
                        type: "uint8",
                      },
                    ],
                    internalType: "struct IStrategyVault.Parameter",
                    name: "parameterReplacement",
                    type: "tuple",
                  },
                ],
                internalType: "struct IStrategyVault.ContextKey[]",
                name: "inputs",
                type: "tuple[]",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "key",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "offset",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "length",
                        type: "uint256",
                      },
                      {
                        internalType: "enum IStrategyVault.ParamType",
                        name: "paramType",
                        type: "uint8",
                      },
                    ],
                    internalType: "struct IStrategyVault.Parameter",
                    name: "parameterReplacement",
                    type: "tuple",
                  },
                ],
                internalType: "struct IStrategyVault.ContextKey",
                name: "output",
                type: "tuple",
              },
              {
                internalType: "uint8",
                name: "result",
                type: "uint8",
              },
            ],
            internalType: "struct IStrategyVault.Action[]",
            name: "actions",
            type: "tuple[]",
          },
        ],
        internalType: "struct IStrategyVault.StrategyStep[]",
        name: "steps",
        type: "tuple[]",
      },
      {
        internalType: "bytes32",
        name: "contextId",
        type: "bytes32",
      },
    ],
    name: "createStrategyWithExistingContext",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "deleteAutomation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "deleteStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "beneficary",
        type: "address",
      },
    ],
    name: "executeAutomation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "executeStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contextId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
    ],
    name: "getContextVariable",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "contextId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
      {
        internalType: "enum IStrategyVault.ParamType",
        name: "paramType",
        type: "uint8",
      },
      {
        internalType: "bytes",
        name: "value",
        type: "bytes",
      },
    ],
    name: "storeConextVariable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "id",
        type: "uint32",
      },
    ],
    name: "strategy",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            components: [
              {
                components: [
                  {
                    internalType: "address",
                    name: "conditionAddress",
                    type: "address",
                  },
                  {
                    internalType: "uint32",
                    name: "id",
                    type: "uint32",
                  },
                  {
                    internalType: "uint8",
                    name: "result1",
                    type: "uint8",
                  },
                  {
                    internalType: "uint8",
                    name: "result0",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Condition",
                name: "condition",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes4",
                    name: "selector",
                    type: "bytes4",
                  },
                  {
                    internalType: "bytes",
                    name: "parameter",
                    type: "bytes",
                  },
                  {
                    internalType: "address",
                    name: "target",
                    type: "address",
                  },
                  {
                    internalType: "uint256",
                    name: "value",
                    type: "uint256",
                  },
                  {
                    internalType: "enum IStrategyVault.ActionType",
                    name: "actionType",
                    type: "uint8",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "key",
                        type: "bytes32",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "offset",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "length",
                            type: "uint256",
                          },
                          {
                            internalType: "enum IStrategyVault.ParamType",
                            name: "paramType",
                            type: "uint8",
                          },
                        ],
                        internalType: "struct IStrategyVault.Parameter",
                        name: "parameterReplacement",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct IStrategyVault.ContextKey[]",
                    name: "inputs",
                    type: "tuple[]",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "key",
                        type: "bytes32",
                      },
                      {
                        components: [
                          {
                            internalType: "uint256",
                            name: "offset",
                            type: "uint256",
                          },
                          {
                            internalType: "uint256",
                            name: "length",
                            type: "uint256",
                          },
                          {
                            internalType: "enum IStrategyVault.ParamType",
                            name: "paramType",
                            type: "uint8",
                          },
                        ],
                        internalType: "struct IStrategyVault.Parameter",
                        name: "parameterReplacement",
                        type: "tuple",
                      },
                    ],
                    internalType: "struct IStrategyVault.ContextKey",
                    name: "output",
                    type: "tuple",
                  },
                  {
                    internalType: "uint8",
                    name: "result",
                    type: "uint8",
                  },
                ],
                internalType: "struct IStrategyVault.Action[]",
                name: "actions",
                type: "tuple[]",
              },
            ],
            internalType: "struct IStrategyVault.StrategyStep[]",
            name: "steps",
            type: "tuple[]",
          },
          {
            internalType: "bytes32",
            name: "contextId",
            type: "bytes32",
          },
        ],
        internalType: "struct IStrategyVault.Strategy",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStrategyVault__factory {
  static readonly abi = _abi;
  static createInterface(): IStrategyVaultInterface {
    return new Interface(_abi) as IStrategyVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStrategyVault {
    return new Contract(address, _abi, runner) as unknown as IStrategyVault;
  }
}
